### ISSUE TITLE
Do I have to define 2 clients, the view and content client?

### ISSUE THREAD

**Issue by kjtigue** [adammbalogh/box-php-sdk#3]
i am using another api for the authentication.
can i set the access token to box?
but view box uses api key.

but when i tried them all,
they were null.
pls help. i am using artdarek as my authenticaiton in laravel 4

**Comment by adammbalogh** [comment]
You can inject your access token to your Content Client. See the [documentation](https://github.com/adammbalogh/box-php-sdk#create-client).
