### ISSUE TITLE
Getting Access Token Through Refresh Token

### ISSUE THREAD

**Issue by Gauhar** [adammbalogh/box-php-sdk#5]
Hi,
When I use this library to get the authentication it gives me the access token. When the response comes the refresh token is also sent in the response along with the access token. According to the box.com api, the access token is expired after 1 hour but the refresh token is expired after 60 days. We can get access token through the refresh token. It seems there is no way in this library to get access token through the refresh token. 

It would be super awesome if you could help me with that.
Apart from this issue the library works like a charm. Thanks

**Comment by adammbalogh** [comment]
If your access token is expired and you call the `authorize`method it will try to get a new access token through the refresh token. [code link](https://github.com/adammbalogh/box-php-sdk/blob/master/src/Client/OAuthClient.php#L81)
