### ISSUE TITLE
Guzzle 6.2

### ISSUE THREAD

**Issue by ryanvade** [adammbalogh/box-php-sdk#8]
I'm on Laravel 5.2 which uses Guzzle 6.2.  Is there any way to bump up the Guzzle version required by box-php-sdk to 6.2?

**Comment by wapmorgan** [comment]
Agreed with that man. Need to update guzzle version!

**Comment by Frost007** [comment]
Same here. Can we get an update?

**Comment by ryanvade** [comment]
I have implemented a few Libraries for use with Box that may be useful to people. 

The first is an adapter to Flysystem: https://github.com/ryanvade/flysystem-box
The other is a Laravel package: https://github.com/ryanvade/laravel-box

Feel free to fork them or use them as you wish.

**Comment by paulm17** [comment]
Not using Laravel here, would like to see an update as well!

Many thanks
